<?php $post = $this->getPost();?>
<?php if($post):?>
    <div class="featured-wordpress-post featured-section <?php echo $this->getDisplayClass();?>">
        <a href="<?php echo $post->getPermalink()?>">
            <p class="section-title"><?php echo $post->getPostTitle();?></p>
            <?php if($this->hasFeaturedImage()):?>
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$this->getFeaturedImage();?>" />
            <?php endif;?>
        </a>
    </div>
<?php endif;?>